In [43]:
# Import dependencies
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import re

In [2]:
# [Pos, No, Driver, Car, Race Laps, Time/Retired, Race PTS], [Fastest Lap, Time of day, Fastest Lap Time, Avg Speed], [Total Stops], [Starting Grid Position, Final Qualifying Time], [Q1 Time, Q2 Time, Q3 Time, Qualifying Laps]
bahrain_df = pd.DataFrame()

In [3]:
# Import race result data
df_0_0 = pd.read_csv("./data/0_0_df.csv")
df_0_0.head(1)

,Unnamed: 0,Pos,No,Driver,Car,Laps,Time/Retired,PTS,Unnamed: 8
0,NaN,1,16,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,NaN

In [4]:
bahrain_df['Final Race Position'] = df_0_0['Pos']
bahrain_df['No'] = df_0_0['No']
bahrain_df['Driver Name'] = df_0_0['Driver']
bahrain_df['Car'] = df_0_0['Car']
bahrain_df['Race Laps'] = df_0_0['Laps']
bahrain_df['Race Time'] = df_0_0['Time/Retired']
bahrain_df['Race Points'] = df_0_0['PTS']
bahrain_df.set_index('No', inplace=True)

In [5]:
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points
No,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15
63,4,George Russell RUS,Mercedes,57,+11.211s,12
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10

In [6]:
# Import fastest lap data
df_0_1 = pd.read_csv("./data/0_1_df.csv")
df_0_1.set_index('No', inplace=True)
df_0_1.head(1)

,Unnamed: 0,Pos,Driver,Car,Lap,Time of day,Time,Avg Speed,Unnamed: 9
No,,,,,,,,,
16,NaN,1,Charles Leclerc LEC,Ferrari,51,19:31:35,1:34.570,206.018,NaN

In [7]:
bahrain_df = bahrain_df.join(df_0_1[['Lap', 'Time of day', 'Time', 'Avg Speed']], on='No')
bahrain_df.head(1)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Lap,Time of day,Time,Avg Speed
No,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018

In [8]:
# Import pit stop data
df_0_2 = pd.read_csv("./data/0_2_df.csv")
df_0_2.set_index('No', inplace=True)
df_0_2.sort_values(by=['Driver', 'Stops'])
df_0_2.drop_duplicates(subset=['Driver'], keep='last', inplace=True)
df_0_2

,Unnamed: 0,Stops,Driver,Car,Lap,Time of day,Time,Total,Unnamed: 9
No,,,,,,,,,
10,NaN,2,Pierre Gasly GAS,AlphaTauri RBPT,32,18:57:23,25.875,50.450,NaN
47,NaN,2,Mick Schumacher MSC,Haas Ferrari,35,19:02:58,25.586,50.800,NaN
14,NaN,3,Fernando Alonso ALO,Alpine Renault,42,19:14:26,24.508,1:14.782,NaN
1,NaN,3,Max Verstappen VER,Red Bull Racing RBPT,43,19:14:40,24.402,1:14.236,NaN
11,NaN,3,Sergio Perez PER,Red Bull Racing RBPT,43,19:14:56,24.947,1:14.166,NaN
31,NaN,3,Esteban Ocon OCO,Alpine Renault,43,19:15:58,24.233,1:20.110,NaN
55,NaN,3,Carlos Sainz SAI,Ferrari,44,19:16:30,24.287,1:13.391,NaN
44,NaN,3,Lewis Hamilton HAM,Mercedes,44,19:16:52,25.579,1:16.576,NaN
22,NaN,3,Yuki Tsunoda TSU,AlphaTauri RBPT,44,19:17:39,24.188,1:14.633,NaN
3,NaN,3,Daniel Ricciardo RIC,McLaren Mercedes,44,19:18:41,25.139,1:14.939,NaN
63,NaN,3,George Russell RUS,Mercedes,45,19:18:53,25.574,1:16.796,NaN
27,NaN,3,Nico Hulkenberg HUL,Aston Martin Aramco Mercedes,44,19:18:58,25.748,1:19.825,NaN
77,NaN,3,Valtteri Bottas BOT,Alfa Romeo Ferrari,45,19:19:39,25.188,1:16.237,NaN
24,NaN,3,Zhou Guanyu ZHO,Alfa Romeo Ferrari,45,19:19:45,28.647,1:19.366,NaN
16,NaN,3,Charles Leclerc LEC,Ferrari,46,19:19:53,24.613,1:14.152,NaN
18,NaN,3,Lance Stroll STR,Aston Martin Aramco Mercedes,45,19:20:32,25.039,1:17.735,NaN
4,NaN,3,Lando Norris NOR,McLaren Mercedes,45,19:20:59,24.975,1:16.910,NaN
6,NaN,3,Nicholas Latifi LAT,Williams Mercedes,45,19:21:07,24.658,1:13.893,NaN
20,NaN,3,Kevin Magnussen MAG,Haas Ferrari,46,19:21:29,26.051,1:17.405,NaN
23,NaN,3,Alexander Albon ALB,Williams Mercedes,46,19:22:54,25.055,1:15.499,NaN

In [9]:
bahrain_df = bahrain_df.join(df_0_2[['Stops', 'Total']], on='No')
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Lap,Time of day,Time,Avg Speed,Stops,Total
No,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,3,1:14.152
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,3,1:13.391
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,3,1:16.576
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,3,1:16.796
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,3,1:17.405

In [10]:
bahrain_df.rename(columns={"Time": "Fastest Lap Time"}, inplace=True)

In [11]:
# Import starting grid data
df_0_3 = pd.read_csv("./data/0_3_df.csv")
df_0_3.set_index('No', inplace=True)
df_0_3.head(1)

    Unnamed: 0  Pos                 Driver      Car      Time  Unnamed: 6
No
16         NaN    1  Charles  Leclerc  LEC  Ferrari  1:30.558         NaN

In [12]:
bahrain_df = bahrain_df.join(df_0_3[['Pos', 'Time']], on='No')
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Lap,Time of day,Fastest Lap Time,Avg Speed,Stops,Total,Pos,Time
No,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,3,1:14.152,1,1:30.558
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,3,1:13.391,3,1:30.687
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,3,1:16.576,5,1:31.238
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,3,1:16.796,9,1:32.216
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,3,1:17.405,7,1:31.808

In [13]:
bahrain_df.rename(columns={"Lap": "Fastest Lap No", "Total": "Total Pit Time", "Pos": "Starting Grid Pos", "Time": "Starting Grid Quali Time"}, inplace=True)
bahrain_df.head(1)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,Stops,Total Pit Time,Starting Grid Pos,Starting Grid Quali Time
No,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,3,1:14.152,1,1:30.558

In [14]:
# Import qualifying data
df_0_4 = pd.read_csv("./data/0_4_df.csv")
df_0_4.set_index('No', inplace=True)
df_0_4.head(1)

,Unnamed: 0,Pos,Driver,Car,Q1,Q2,Q3,Laps,Unnamed: 9
No,,,,,,,,,
16,NaN,1,Charles Leclerc LEC,Ferrari,1:31.471,1:30.932,1:30.558,15,NaN

In [15]:
bahrain_df = bahrain_df.join(df_0_4[['Pos', 'Q1', 'Q2', 'Q3', 'Laps']], on='No')
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,Stops,Total Pit Time,Starting Grid Pos,Starting Grid Quali Time,Pos,Q1,Q2,Q3,Laps
No,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,3,1:14.152,1,1:30.558,1,1:31.471,1:30.932,1:30.558,15
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,3,1:13.391,3,1:30.687,3,1:31.567,1:30.787,1:30.687,15
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,3,1:16.576,5,1:31.238,5,1:32.285,1:31.048,1:31.238,17
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,3,1:16.796,9,1:32.216,9,1:32.269,1:31.252,1:32.216,17
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,3,1:17.405,7,1:31.808,7,1:31.955,1:31.461,1:31.808,12

In [16]:
bahrain_df.rename(columns={"Pos": "Qualifying Postition", "Laps": "Qualifying Laps"}, inplace=True)
bahrain_df.head(1)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,Stops,Total Pit Time,Starting Grid Pos,Starting Grid Quali Time,Qualifying Postition,Q1,Q2,Q3,Qualifying Laps
No,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,3,1:14.152,1,1:30.558,1,1:31.471,1:30.932,1:30.558,15

In [17]:
# Import P3 data
df_0_5 = pd.read_csv("./data/0_5_df.csv")
df_0_5.set_index('No', inplace=True)
df_0_5

,Unnamed: 0,Pos,Driver,Car,Time,Gap,Laps,Unnamed: 8
No,,,,,,,,
1,NaN,1,Max Verstappen VER,Red Bull Racing RBPT,1:32.544,NaN,15,NaN
16,NaN,2,Charles Leclerc LEC,Ferrari,1:32.640,+0.096s,16,NaN
11,NaN,3,Sergio Perez PER,Red Bull Racing RBPT,1:32.791,+0.247s,20,NaN
63,NaN,4,George Russell RUS,Mercedes,1:32.935,+0.391s,19,NaN
55,NaN,5,Carlos Sainz SAI,Ferrari,1:33.053,+0.509s,20,NaN
44,NaN,6,Lewis Hamilton HAM,Mercedes,1:33.121,+0.577s,15,NaN
20,NaN,7,Kevin Magnussen MAG,Haas Ferrari,1:33.437,+0.893s,15,NaN
77,NaN,8,Valtteri Bottas BOT,Alfa Romeo Ferrari,1:33.733,+1.189s,21,NaN
24,NaN,9,Zhou Guanyu ZHO,Alfa Romeo Ferrari,1:33.880,+1.336s,18,NaN
18,NaN,10,Lance Stroll STR,Aston Martin Aramco Mercedes,1:33.920,+1.376s,14,NaN
4,NaN,11,Lando Norris NOR,McLaren Mercedes,1:33.955,+1.411s,18,NaN
27,NaN,12,Nico Hulkenberg HUL,Aston Martin Aramco Mercedes,1:33.971,+1.427s,18,NaN
10,NaN,13,Pierre Gasly GAS,AlphaTauri RBPT,1:34.176,+1.632s,18,NaN
47,NaN,14,Mick Schumacher MSC,Haas Ferrari,1:34.295,+1.751s,17,NaN
3,NaN,15,Daniel Ricciardo RIC,McLaren Mercedes,1:34.378,+1.834s,20,NaN
14,NaN,16,Fernando Alonso ALO,Alpine Renault,1:34.628,+2.084s,15,NaN
23,NaN,17,Alexander Albon ALB,Williams Mercedes,1:34.868,+2.324s,15,NaN
31,NaN,18,Esteban Ocon OCO,Alpine Renault,1:34.957,+2.413s,16,NaN
6,NaN,19,Nicholas Latifi LAT,Williams Mercedes,1:35.667,+3.123s,14,NaN

In [18]:
bahrain_df = bahrain_df.join(df_0_5[['Pos', 'Time', 'Gap', 'Laps']], on='No')
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,Starting Grid Quali Time,Qualifying Postition,Q1,Q2,Q3,Qualifying Laps,Pos,Time,Gap,Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,1:30.558,1,1:31.471,1:30.932,1:30.558,15,2.0,1:32.640,+0.096s,16.0
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,...,1:30.687,3,1:31.567,1:30.787,1:30.687,15,5.0,1:33.053,+0.509s,20.0
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,...,1:31.238,5,1:32.285,1:31.048,1:31.238,17,6.0,1:33.121,+0.577s,15.0
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,...,1:32.216,9,1:32.269,1:31.252,1:32.216,17,4.0,1:32.935,+0.391s,19.0
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,...,1:31.808,7,1:31.955,1:31.461,1:31.808,12,7.0,1:33.437,+0.893s,15.0

In [19]:
bahrain_df.rename(columns={"Pos": "P3 Postition", "Time": "P3 Time", "Gap": "P3 Gap", "Laps": "P3 Laps"}, inplace=True)
bahrain_df.head(1)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,Starting Grid Quali Time,Qualifying Postition,Q1,Q2,Q3,Qualifying Laps,P3 Postition,P3 Time,P3 Gap,P3 Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,1:30.558,1,1:31.471,1:30.932,1:30.558,15,2.0,1:32.640,+0.096s,16.0

In [20]:
# Import P2 data
df_0_6 = pd.read_csv("./data/0_6_df.csv")
df_0_6.set_index('No', inplace=True)
df_0_6.head(1)

,Unnamed: 0,Pos,Driver,Car,Time,Gap,Laps,Unnamed: 8
No,,,,,,,,
1,NaN,1,Max Verstappen VER,Red Bull Racing RBPT,1:31.936,NaN,20,NaN

In [21]:
bahrain_df = bahrain_df.join(df_0_6[['Pos', 'Time', 'Gap', 'Laps']], on='No')
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,Q3,Qualifying Laps,P3 Postition,P3 Time,P3 Gap,P3 Laps,Pos,Time,Gap,Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,1:30.558,15,2.0,1:32.640,+0.096s,16.0,2,1:32.023,+0.087s,20
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,...,1:30.687,15,5.0,1:33.053,+0.509s,20.0,3,1:32.520,+0.584s,22
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,...,1:31.238,17,6.0,1:33.121,+0.577s,15.0,9,1:33.144,+1.208s,23
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,...,1:32.216,17,4.0,1:32.935,+0.391s,19.0,4,1:32.529,+0.593s,25
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,...,1:31.808,12,7.0,1:33.437,+0.893s,15.0,10,1:33.183,+1.247s,23

In [22]:
bahrain_df.rename(columns={"Pos": "P2 Postition", "Time": "P2 Time", "Gap": "P2 Gap", "Laps": "P2 Laps"}, inplace=True)
bahrain_df.head(1)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,Q3,Qualifying Laps,P3 Postition,P3 Time,P3 Gap,P3 Laps,P2 Postition,P2 Time,P2 Gap,P2 Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,1:30.558,15,2.0,1:32.640,+0.096s,16.0,2,1:32.023,+0.087s,20

In [23]:
# Import P1 data
df_0_7 = pd.read_csv("./data/0_7_df.csv")
df_0_7.set_index('No', inplace=True)
df_0_7.head(1)

,Unnamed: 0,Pos,Driver,Car,Time,Gap,Laps,Unnamed: 8
No,,,,,,,,
10,NaN,1,Pierre Gasly GAS,AlphaTauri RBPT,1:34.193,NaN,23,NaN

In [24]:
bahrain_df = bahrain_df.join(df_0_6[['Pos', 'Time', 'Gap', 'Laps']], on='No')
bahrain_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,P3 Gap,P3 Laps,P2 Postition,P2 Time,P2 Gap,P2 Laps,Pos,Time,Gap,Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,+0.096s,16.0,2,1:32.023,+0.087s,20,2,1:32.023,+0.087s,20
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,...,+0.509s,20.0,3,1:32.520,+0.584s,22,3,1:32.520,+0.584s,22
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,...,+0.577s,15.0,9,1:33.144,+1.208s,23,9,1:33.144,+1.208s,23
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,...,+0.391s,19.0,4,1:32.529,+0.593s,25,4,1:32.529,+0.593s,25
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,...,+0.893s,15.0,10,1:33.183,+1.247s,23,10,1:33.183,+1.247s,23

In [25]:
bahrain_df.rename(columns={"Pos": "P1 Postition", "Time": "P1 Time", "Gap": "P1 Gap", "Laps": "P1 Laps"}, inplace=True)
bahrain_df.head(1)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,P3 Gap,P3 Laps,P2 Postition,P2 Time,P2 Gap,P2 Laps,P1 Postition,P1 Time,P1 Gap,P1 Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,+0.096s,16.0,2,1:32.023,+0.087s,20,2,1:32.023,+0.087s,20

In [26]:
bahrain_df

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,P3 Gap,P3 Laps,P2 Postition,P2 Time,P2 Gap,P2 Laps,P1 Postition,P1 Time,P1 Gap,P1 Laps
No,,,,,,,,,,,,,,,,,,,,,
16,1,Charles Leclerc LEC,Ferrari,57,1:37:33.584,26,51,19:31:35,1:34.570,206.018,...,+0.096s,16.0,2,1:32.023,+0.087s,20,2,1:32.023,+0.087s,20
55,2,Carlos Sainz SAI,Ferrari,57,+5.598s,18,52,19:33:13,1:35.740,203.501,...,+0.509s,20.0,3,1:32.520,+0.584s,22,3,1:32.520,+0.584s,22
44,3,Lewis Hamilton HAM,Mercedes,57,+9.675s,15,53,19:34:51,1:36.228,202.469,...,+0.577s,15.0,9,1:33.144,+1.208s,23,9,1:33.144,+1.208s,23
63,4,George Russell RUS,Mercedes,57,+11.211s,12,56,19:39:42,1:36.302,202.313,...,+0.391s,19.0,4,1:32.529,+0.593s,25,4,1:32.529,+0.593s,25
20,5,Kevin Magnussen MAG,Haas Ferrari,57,+14.754s,10,53,19:34:54,1:36.623,201.641,...,+0.893s,15.0,10,1:33.183,+1.247s,23,10,1:33.183,+1.247s,23
77,6,Valtteri Bottas BOT,Alfa Romeo Ferrari,57,+16.119s,8,53,19:34:55,1:36.599,201.691,...,+1.189s,21.0,6,1:32.951,+1.015s,30,6,1:32.951,+1.015s,30
31,7,Esteban Ocon OCO,Alpine Renault,57,+19.423s,6,53,19:34:56,1:37.110,200.630,...,+2.413s,16.0,12,1:33.360,+1.424s,25,12,1:33.360,+1.424s,25
22,8,Yuki Tsunoda TSU,AlphaTauri RBPT,57,+20.386s,4,53,19:34:57,1:37.104,200.642,...,NaN,NaN,14,1:33.789,+1.853s,26,14,1:33.789,+1.853s,26
14,9,Fernando Alonso ALO,Alpine Renault,57,+22.390s,2,44,19:18:02,1:36.733,201.412,...,+2.084s,15.0,5,1:32.877,+0.941s,24,5,1:32.877,+0.941s,24
24,10,Zhou Guanyu ZHO,Alfa Romeo Ferrari,57,+23.064s,1,39,19:09:38,1:36.685,201.512,...,+1.336s,18.0,15,1:33.953,+2.017s,27,15,1:33.953,+2.017s,27
47,11,Mick Schumacher MSC,Haas Ferrari,57,+32.574s,0,37,19:06:35,1:36.956,200.948,...,+1.751s,17.0,8,1:33.085,+1.149s,24,8,1:33.085,+1.149s,24
18,12,Lance Stroll STR,Aston Martin Aramco Mercedes,57,+45.873s,0,49,19:28:47,1:37.146,200.555,...,+1.376s,14.0,16,1:33.958,+2.022s,25,16,1:33.958,+2.022s,25
23,13,Alexander Albon ALB,Williams Mercedes,57,+53.932s,0,50,19:30:32,1:37.355,200.125,...,+2.324s,15.0,20,1:34.735,+2.799s,22,20,1:34.735,+2.799s,22
3,14,Daniel Ricciardo RIC,McLaren Mercedes,57,+54.975s,0,50,19:30:34,1:37.261,200.318,...,+1.834s,20.0,18,1:34.166,+2.230s,12,18,1:34.166,+2.230s,12
4,15,Lando Norris NOR,McLaren Mercedes,57,+56.335s,0,51,19:32:13,1:36.988,200.882,...,+1.411s,18.0,11,1:33.280,+1.344s,27,11,1:33.280,+1.344s,27
6,16,Nicholas Latifi LAT,Williams Mercedes,57,+61.795s,0,51,19:32:16,1:38.251,198.300,...,+3.123s,14.0,19,1:34.486,+2.550s,28,19,1:34.486,+2.550s,28
27,17,Nico Hulkenberg HUL,Aston Martin Aramco Mercedes,57,+63.829s,0,49,19:29:00,1:38.201,198.401,...,+1.427s,18.0,17,1:34.061,+2.125s,28,17,1:34.061,+2.125s,28
11,18,Sergio Perez PER,Red Bull Racing RBPT,56,DNF,0,52,19:33:14,1:36.089,202.762,...,+0.247s,20.0,7,1:32.958,+1.022s,20,7,1:32.958,+1.022s,20
1,19,Max Verstappen VER,Red Bull Racing RBPT,54,DNF,0,51,19:31:37,1:35.440,204.140,...,NaN,15.0,1,1:31.936,NaN,20,1,1:31.936,NaN,20
10,NC,Pierre Gasly GAS,AlphaTauri RBPT,44,DNF,0,34,19:01:03,1:37.324,200.189,...,+1.632s,18.0,13,1:33.621,+1.685s,24,13,1:33.621,+1.685s,24

# Sprint Race DF Flow

In [27]:
italy_df = pd.DataFrame()

df_3_0 = pd.read_csv("./data/3_0_df.csv")

italy_df['Final Race Position'] = df_3_0['Pos']
italy_df['No'] = df_3_0['No']
italy_df['Driver Name'] = df_3_0['Driver']
italy_df['Car'] = df_3_0['Car']
italy_df['Race Laps'] = df_3_0['Laps']
italy_df['Race Time'] = df_3_0['Time/Retired']
italy_df['Race Points'] = df_3_0['PTS']
italy_df.set_index('No', inplace=True)

df_3_1 = pd.read_csv("./data/3_1_df.csv")
df_3_1.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_1[['Lap', 'Time of day', 'Time', 'Avg Speed']], on='No')
italy_df.rename(columns={"Lap": "Fastest Lap No", "Time": "Fastest Lap Time"}, inplace=True)

df_3_2 = pd.read_csv("./data/3_2_df.csv")
df_3_2.set_index('No', inplace=True)
df_3_2.sort_values(by=['Driver', 'Stops'])
df_3_2.drop_duplicates(subset=['Driver'], keep='last', inplace=True)

italy_df = italy_df.join(df_3_2[['Stops', 'Total']], on='No')
italy_df.rename(columns={"Total": "Total Pit Time"}, inplace=True)

df_3_3 = pd.read_csv("./data/3_3_df.csv")
df_3_3.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_3[['Pos']], on='No')
italy_df.rename(columns={"Pos": "Starting Grid Pos"}, inplace=True)

df_3_4 = pd.read_csv("./data/3_4_df.csv")
df_3_4.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_4[['Pos', 'Laps', 'Time/Retired', 'PTS']], on='No')
italy_df.rename(columns={"Pos": "Final Sprint Postition", "Laps": "Sprint Laps", "Time/Retired": "Sprint Time/Retired", "PTS": "Sprint PTS"}, inplace=True)

df_3_5 = pd.read_csv("./data/3_5_df.csv")
df_3_5.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_5[['Pos', 'Time']], on='No')
italy_df.rename(columns={"Pos": "Starting Sprint Postition", "Time": "Sprint Grid Time"}, inplace=True)

df_3_6 = pd.read_csv("./data/3_6_df.csv")
df_3_6.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_6[['Pos', 'Time', 'Gap', 'Laps']], on='No')
italy_df.rename(columns={"Pos": "P2 Postition", "Time": "P2 Time", "Gap": "P2 Gap", "Laps": "P2 Laps"}, inplace=True)

df_3_7 = pd.read_csv("./data/3_7_df.csv")
df_3_7.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_7[['Pos', 'Q1', 'Q2', 'Q3', 'Laps']], on='No')
italy_df.rename(columns={"Pos": "Qualifying Postition", "Laps": "Qualifying Laps"}, inplace=True)

df_3_8 = pd.read_csv("./data/3_8_df.csv")
df_3_8.set_index('No', inplace=True)

italy_df = italy_df.join(df_3_8[['Pos', 'Time', 'Gap', 'Laps']], on='No')
italy_df.rename(columns={"Pos": "P1 Postition", "Time": "P1 Time", "Gap": "P1 Gap", "Laps": "P1 Laps"}, inplace=True)
italy_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,P2 Laps,Qualifying Postition,Q1,Q2,Q3,Qualifying Laps,P1 Postition,P1 Time,P1 Gap,P1 Laps
No,,,,,,,,,,,,,,,,,,,,,
1,1,Max Verstappen VER,Red Bull Racing RBPT,63,1:32:07.986,26,55.0,16:24:32,1:18.446,225.281,...,36.0,1,1:19.295,1:18.793,1:27.999,22,3,1:30.867,+1.465s,21
11,2,Sergio Perez PER,Red Bull Racing RBPT,63,+16.527s,18,52.0,16:20:46,1:18.949,223.845,...,33.0,7,1:19.773,1:19.296,1:29.808,25,6,1:33.012,+3.610s,17
4,3,Lando Norris NOR,McLaren Mercedes,63,+34.834s,15,61.0,16:33:03,1:20.903,218.439,...,6.0,3,1:20.168,1:19.294,1:29.131,22,14,1:35.502,+6.100s,12
63,4,George Russell RUS,Mercedes,63,+42.506s,12,57.0,16:27:45,1:20.962,218.280,...,32.0,11,1:20.383,1:20.757,NaN,16,10,1:34.262,+4.860s,21
77,5,Valtteri Bottas BOT,Alfa Romeo Ferrari,63,+43.181s,10,43.0,16:08:51,1:20.758,218.831,...,NaN,8,1:20.419,1:20.192,1:30.439,23,11,1:34.615,+5.213s,19

In [28]:
italy_df

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,P2 Laps,Qualifying Postition,Q1,Q2,Q3,Qualifying Laps,P1 Postition,P1 Time,P1 Gap,P1 Laps
No,,,,,,,,,,,,,,,,,,,,,
1,1,Max Verstappen VER,Red Bull Racing RBPT,63,1:32:07.986,26,55.0,16:24:32,1:18.446,225.281,...,36.0,1,1:19.295,1:18.793,1:27.999,22,3,1:30.867,+1.465s,21
11,2,Sergio Perez PER,Red Bull Racing RBPT,63,+16.527s,18,52.0,16:20:46,1:18.949,223.845,...,33.0,7,1:19.773,1:19.296,1:29.808,25,6,1:33.012,+3.610s,17
4,3,Lando Norris NOR,McLaren Mercedes,63,+34.834s,15,61.0,16:33:03,1:20.903,218.439,...,6.0,3,1:20.168,1:19.294,1:29.131,22,14,1:35.502,+6.100s,12
63,4,George Russell RUS,Mercedes,63,+42.506s,12,57.0,16:27:45,1:20.962,218.280,...,32.0,11,1:20.383,1:20.757,NaN,16,10,1:34.262,+4.860s,21
77,5,Valtteri Bottas BOT,Alfa Romeo Ferrari,63,+43.181s,10,43.0,16:08:51,1:20.758,218.831,...,NaN,8,1:20.419,1:20.192,1:30.439,23,11,1:34.615,+5.213s,19
16,6,Charles Leclerc LEC,Ferrari,63,+56.072s,8,63.0,16:36:07,1:18.574,224.914,...,35.0,2,1:18.796,1:19.584,1:28.778,22,1,1:29.402,NaN,24
22,7,Yuki Tsunoda TSU,AlphaTauri RBPT,63,+61.110s,6,61.0,16:33:29,1:20.544,219.412,...,35.0,16,1:20.474,NaN,NaN,11,9,1:33.611,+4.209s,18
5,8,Sebastian Vettel VET,Aston Martin Aramco Mercedes,63,+70.892s,4,47.0,16:14:34,1:21.211,217.610,...,38.0,9,1:20.364,1:19.957,1:31.062,25,8,1:33.365,+3.963s,22
20,9,Kevin Magnussen MAG,Haas Ferrari,63,+75.260s,2,61.0,16:33:43,1:21.238,217.538,...,30.0,4,1:20.147,1:19.902,1:29.164,21,4,1:32.439,+3.037s,23
18,10,Lance Stroll STR,Aston Martin Aramco Mercedes,62,+1 lap,1,46.0,16:13:27,1:21.750,216.176,...,38.0,15,1:20.342,1:28.119,NaN,14,16,1:36.033,+6.631s,23
23,11,Alexander Albon ALB,Williams Mercedes,62,+1 lap,0,61.0,16:34:02,1:21.757,216.157,...,34.0,NC,DNF,NaN,NaN,3,17,1:36.461,+7.059s,17
10,12,Pierre Gasly GAS,AlphaTauri RBPT,62,+1 lap,0,34.0,15:57:05,1:21.713,216.274,...,37.0,17,1:20.732,NaN,NaN,11,12,1:35.104,+5.702s,19
44,13,Lewis Hamilton HAM,Mercedes,62,+1 lap,0,50.0,16:19:00,1:21.419,217.054,...,34.0,13,1:20.470,1:21.138,NaN,15,18,1:36.464,+7.062s,17
31,14,Esteban Ocon OCO,Alpine Renault,62,+1 lap,0,37.0,16:01:09,1:21.887,215.814,...,30.0,19,1:22.338,NaN,NaN,9,13,1:35.420,+6.018s,14
24,15,Zhou Guanyu ZHO,Alfa Romeo Ferrari,62,+1 lap,0,61.0,16:34:13,1:21.286,217.410,...,32.0,14,1:19.730,1:21.434,NaN,16,19,1:37.450,+8.048s,22
6,16,Nicholas Latifi LAT,Williams Mercedes,62,+1 lap,0,62.0,16:35:37,1:21.338,217.271,...,31.0,18,1:21.971,NaN,NaN,13,20,1:39.698,+10.296s,15
47,17,Mick Schumacher MSC,Haas Ferrari,62,+1 lap,0,55.0,16:26:33,1:18.999,223.704,...,29.0,12,1:20.422,1:20.916,NaN,16,5,1:32.988,+3.586s,23
3,18,Daniel Ricciardo RIC,McLaren Mercedes,62,+1 lap,0,61.0,16:34:47,1:21.577,216.634,...,NaN,6,1:19.980,1:20.031,1:29.742,21,15,1:35.625,+6.223s,15
14,NC,Fernando Alonso ALO,Alpine Renault,6,DNF,0,5.0,15:13:47,1:39.685,177.282,...,29.0,5,1:20.198,1:19.595,1:29.202,26,7,1:33.160,+3.758s,13
55,NC,Carlos Sainz SAI,Ferrari,0,DNF,0,NaN,NaN,NaN,NaN,...,31.0,10,1:19.305,1:18.990,NaN,13,2,1:30.279,+0.877s,25

# Data Cleaning

In [29]:
italy_df.head(5)

,Final Race Position,Driver Name,Car,Race Laps,Race Time,Race Points,Fastest Lap No,Time of day,Fastest Lap Time,Avg Speed,...,P2 Laps,Qualifying Postition,Q1,Q2,Q3,Qualifying Laps,P1 Postition,P1 Time,P1 Gap,P1 Laps
No,,,,,,,,,,,,,,,,,,,,,
1,1,Max Verstappen VER,Red Bull Racing RBPT,63,1:32:07.986,26,55.0,16:24:32,1:18.446,225.281,...,36.0,1,1:19.295,1:18.793,1:27.999,22,3,1:30.867,+1.465s,21
11,2,Sergio Perez PER,Red Bull Racing RBPT,63,+16.527s,18,52.0,16:20:46,1:18.949,223.845,...,33.0,7,1:19.773,1:19.296,1:29.808,25,6,1:33.012,+3.610s,17
4,3,Lando Norris NOR,McLaren Mercedes,63,+34.834s,15,61.0,16:33:03,1:20.903,218.439,...,6.0,3,1:20.168,1:19.294,1:29.131,22,14,1:35.502,+6.100s,12
63,4,George Russell RUS,Mercedes,63,+42.506s,12,57.0,16:27:45,1:20.962,218.280,...,32.0,11,1:20.383,1:20.757,NaN,16,10,1:34.262,+4.860s,21
77,5,Valtteri Bottas BOT,Alfa Romeo Ferrari,63,+43.181s,10,43.0,16:08:51,1:20.758,218.831,...,NaN,8,1:20.419,1:20.192,1:30.439,23,11,1:34.615,+5.213s,19

In [30]:
italy_df.columns

Index(['Final Race Position', 'Driver Name', 'Car', 'Race Laps', 'Race Time',
       'Race Points', 'Fastest Lap No', 'Time of day', 'Fastest Lap Time',
       'Avg Speed', 'Stops', 'Total Pit Time', 'Starting Grid Pos',
       'Final Sprint Postition', 'Sprint Laps', 'Sprint Time/Retired',
       'Sprint PTS', 'Starting Sprint Postition', 'Sprint Grid Time',
       'P2 Postition', 'P2 Time', 'P2 Gap', 'P2 Laps', 'Qualifying Postition',
       'Q1', 'Q2', 'Q3', 'Qualifying Laps', 'P1 Postition', 'P1 Time',
       'P1 Gap', 'P1 Laps'],
      dtype='object')

In [31]:
race_time = italy_df['Race Time']
race_time

No
1     1:32:07.986
11       +16.527s
4        +34.834s
63       +42.506s
77       +43.181s
16       +56.072s
22       +61.110s
5        +70.892s
20       +75.260s
18         +1 lap
23         +1 lap
10         +1 lap
44         +1 lap
31         +1 lap
24         +1 lap
6          +1 lap
47         +1 lap
3          +1 lap
14            DNF
55            DNF
Name: Race Time, dtype: object

In [32]:
race_time = race_time.map(lambda x: x.lstrip('+-'))
race_time = race_time.map(lambda x: x.rstrip('s'))
race_time

No
1     1:32:07.986
11         16.527
4          34.834
63         42.506
77         43.181
16         56.072
22         61.110
5          70.892
20         75.260
18          1 lap
23          1 lap
10          1 lap
44          1 lap
31          1 lap
24          1 lap
6           1 lap
47          1 lap
3           1 lap
14            DNF
55            DNF
Name: Race Time, dtype: object

In [33]:
# Convert race time to seconds
end_time = race_time.iloc[0]
my_list = end_time.split(':')
time_f = timedelta(hours=int(my_list[0]),minutes=int(my_list[1]), seconds=float(my_list[2]))
time_f.total_seconds()

5527.986

In [51]:
race_time_copy = race_time.copy()
for count, race in enumerate(race_time):
    # Race time is always first index
    if (count == 0):
        print(f"COUNT: {count} | VALUE: {race} | IN COUNT 0")
        end_time = race
        my_list = end_time.split(':')
        time_f = timedelta(hours=int(my_list[0]),minutes=int(my_list[1]), seconds=float(my_list[2])).total_seconds()
        race_time_copy.iloc[count] = time_f
    # If race contains substring 'lap' indicating 1+ Lap. Will add the number of laps indicated so 1+ Lap 
    # Will add 1 whole lap, 2+ Lap will add two laps, etc.
    elif 'lap' in race:
        print(f"COUNT: {count} | VALUE: {race} | IN LAP")
        race_time_copy.iloc[count] = time_f+(int(race[0])*time_f)
    # Use regex to check if a float value exists
    elif re.match(r'^-?\d+(?:\.\d+)$', race) is not None:
        print(f"COUNT: {count} | VALUE: {race} | IN INSTANCE")
        race_time_copy.iloc[count] = (time_f + float(race))
    # Anything else such as DNF, DSQ will get 999999
    else:
        print(f"COUNT: {count} | VALUE: {race} | IN ELSE")
        race_time_copy.iloc[count] = 999999

COUNT: 0 | VALUE: 1:32:07.986 | IN COUNT 0
COUNT: 1 | VALUE: 16.527 | IN INSTANCE
COUNT: 2 | VALUE: 34.834 | IN INSTANCE
COUNT: 3 | VALUE: 42.506 | IN INSTANCE
COUNT: 4 | VALUE: 43.181 | IN INSTANCE
COUNT: 5 | VALUE: 56.072 | IN INSTANCE
COUNT: 6 | VALUE: 61.110 | IN INSTANCE
COUNT: 7 | VALUE: 70.892 | IN INSTANCE
COUNT: 8 | VALUE: 75.260 | IN INSTANCE
COUNT: 9 | VALUE: 1 lap | IN LAP
COUNT: 10 | VALUE: 1 lap | IN LAP
COUNT: 11 | VALUE: 1 lap | IN LAP
COUNT: 12 | VALUE: 1 lap | IN LAP
COUNT: 13 | VALUE: 1 lap | IN LAP
COUNT: 14 | VALUE: 1 lap | IN LAP
COUNT: 15 | VALUE: 1 lap | IN LAP
COUNT: 16 | VALUE: 1 lap | IN LAP
COUNT: 17 | VALUE: 1 lap | IN LAP
COUNT: 18 | VALUE: DNF | IN ELSE
COUNT: 19 | VALUE: DNF | IN ELSE

In [52]:
race_time_copy

No
1      5527.986
11     5544.513
4       5562.82
63     5570.492
77     5571.167
16     5584.058
22     5589.096
5      5598.878
20     5603.246
18    11055.972
23    11055.972
10    11055.972
44    11055.972
31    11055.972
24    11055.972
6     11055.972
47    11055.972
3     11055.972
14       999999
55       999999
Name: Race Time, dtype: object

In [36]:
race_time

No
1     1:32:07.986
11         16.527
4          34.834
63         42.506
77         43.181
16         56.072
22         61.110
5          70.892
20         75.260
18          1 lap
23          1 lap
10          1 lap
44          1 lap
31          1 lap
24          1 lap
6           1 lap
47          1 lap
3           1 lap
14            DNF
55            DNF
Name: Race Time, dtype: object