In [1]:
import pandas as pd
import numpy as np

In [2]:
# settings to display all columns
pd.set_option("display.max_columns", None)

In [3]:
#data_to_load = "Resources/Final_project_data.csv"
dtl = "Final_project_data_8_11.csv"
df = pd.read_csv(dtl)
df.head(25)

,Race,POS,No,Driver,Car,Laps,Time/Retired,PTS,Fastest Lap,Time,Avg Speed,Num Stops,Stop Lap,Stop TOD,Stop TIme,Stop Total TIme,Starting Grid Position,Starting Grid Qualifying TIme,Q1 Time,Q2 Time,Q3 Time,Qualifying Laps,Practice 1 Position,Practice 1 Time,Practice 1 Gap,Practice 1 Laps,Practice 2 Position,Practice 2 Time,Practice 2 Gap,Practice 2 Laps,Practice 3 Position,Practice 3 Time,Practice 3 Gap,Practice 3 Laps,Sprint Y/N,Sprint Position,Sprint Laps,Sprint Time,Sprint Points
0,Bahrain,1,44.0,Hamilton,NaN,56.0,1:32:03.897,25.0,1:34.015,NaN,207.235,2.0,28.0,18:54:40,24.076,48.915,2.0,1:29.385,1:30.617,1:30.085,1:29.385,18.0,4.0,01:31.9,0.527s,15.0,3.0,01:31.1,0.235s,24.0,2.0,01:31.3,0.739s,14.0,N,NaN,NaN,NaN,NaN
1,Bahrain,2,33.0,Verstappen,NaN,56.0,+0.745s,18.0,1:33.228,NaN,208.984,2.0,39.0,19:12:13,23.848,48.615,1.0,1:28.997,1:30.499,1:30.318,1:28.997,15.0,1.0,01:31.4,NaN,12.0,1.0,01:30.8,NaN,23.0,1.0,01:30.6,NaN,11.0,N,NaN,NaN,NaN,NaN
2,Bahrain,3,77.0,Bottas,NaN,56.0,+37.383s,16.0,1:32.090,NaN,211.566,3.0,54.0,19:36:21,24.566,01:21.7,3.0,1:29.586,1:31.200,1:30.186,1:29.586,17.0,2.0,01:31.7,0.298s,17.0,5.0,01:31.2,0.371s,23.0,4.0,01:31.9,1.278s,16.0,N,NaN,NaN,NaN,NaN
3,Bahrain,4,4.0,Norris,NaN,56.0,+46.466s,12.0,1:34.396,NaN,206.398,2.0,33.0,19:03:11,25.64,50.539,7.0,1:29.974,1:30.902,1:30.099,1:29.974,18.0,3.0,01:31.9,0.503s,20.0,2.0,01:30.9,0.095s,25.0,16.0,01:32.9,2.283s,10.0,N,NaN,NaN,NaN,NaN
4,Bahrain,5,11.0,Perez,NaN,56.0,+52.047s,10.0,1:33.970,NaN,207.334,3.0,38.0,19:11:20,24.191,01:12.3,11.0,1:30.659,1:31.165,1:30.659,NaN,11.0,6.0,01:32.1,0.677s,15.0,10.0,01:31.5,0.656s,23.0,5.0,01:31.9,1.331s,11.0,N,NaN,NaN,NaN,NaN
5,Bahrain,6,16.0,Leclerc,NaN,56.0,+59.090s,8.0,1:34.988,NaN,205.112,2.0,32.0,19:01:40,24.176,49.101,4.0,1:29.678,1:30.691,1:30.010,1:29.678,15.0,5.0,01:32.0,0.599s,14.0,12.0,01:31.6,0.765s,26.0,11.0,01:32.5,1.905s,17.0,N,NaN,NaN,NaN,NaN
6,Bahrain,7,3.0,Ricciardo,NaN,56.0,+66.004s,6.0,1:34.932,NaN,205.233,2.0,32.0,19:01:44,24.655,49.343,6.0,1:29.927,1:30.795,1:30.222,1:29.927,18.0,9.0,01:32.4,1.040s,20.0,6.0,01:31.2,0.383s,22.0,10.0,01:32.5,1.900s,12.0,N,NaN,NaN,NaN,NaN
7,Bahrain,8,55.0,Sainz,NaN,56.0,+67.100s,4.0,1:34.509,NaN,206.151,2.0,37.0,19:09:53,24.341,48.694,8.0,1:30.215,1:31.653,1:30.009,1:30.215,17.0,8.0,01:32.4,0.972s,15.0,4.0,01:31.1,0.280s,26.0,6.0,01:32.1,1.531s,16.0,N,NaN,NaN,NaN,NaN
8,Bahrain,9,22.0,Tsunoda,NaN,56.0,+85.692s,2.0,1:34.761,NaN,205.603,2.0,33.0,19:03:36,24.328,49.374,13.0,1:31.203,1:30.607,1:31.203,NaN,9.0,14.0,01:33.3,1.935s,21.0,7.0,01:31.3,0.447s,23.0,13.0,01:32.7,2.132s,15.0,N,NaN,NaN,NaN,NaN
9,Bahrain,10,18.0,Stroll,NaN,56.0,+86.713s,1.0,1:34.865,NaN,205.378,2.0,28.0,18:55:23,25.525,50.409,10.0,1:30.601,1:31.261,1:30.624,1:30.601,15.0,13.0,01:33.2,1.839s,20.0,8.0,01:31.4,0.546s,24.0,9.0,01:32.4,1.854s,13.0,N,NaN,NaN,NaN,NaN
10,Bahrain,11,7.0,Räikkönen,NaN,56.0,+88.864s,0.0,1:35.192,NaN,204.672,2.0,29.0,18:57:06,24.046,48.153,14.0,1:31.238,1:31.547,1:31.238,NaN,12.0,11.0,01:33.1,1.740s,18.0,16.0,01:31.9,1.015s,15.0,7.0,01:32.2,1.647s,15.0,N,NaN,NaN,NaN,NaN
11,Bahrain,12,99.0,Giovinazzi,NaN,55.0,+1 lap,0.0,1:35.122,NaN,204.823,2.0,30.0,18:58:53,24.223,56.221,12.0,1:30.708,1:30.998,1:30.708,NaN,12.0,10.0,01:32.8,1.392s,16.0,13.0,01:31.7,0.893s,27.0,12.0,01:32.5,1.923s,11.0,N,NaN,NaN,NaN,NaN
12,Bahrain,13,31.0,Ocon,NaN,55.0,+1 lap,0.0,1:35.250,NaN,204.548,2.0,31.0,19:00:29,24.471,49.697,16.0,1:31.724,1:31.724,NaN,NaN,6.0,15.0,01:33.5,2.134s,20.0,11.0,01:31.6,0.754s,24.0,8.0,01:32.4,1.846s,11.0,N,NaN,NaN,NaN,NaN
13,Bahrain,14,63.0,Russell,NaN,55.0,+1 lap,0.0,1:35.036,NaN,205.008,2.0,36.0,19:08:48,24.248,48.869,15.0,1:33.430,1:31.316,1:33.430,NaN,11.0,17.0,01:34.1,2.733s,22.0,17.0,01:32.3,1.484s,28.0,17.0,01:33.3,2.746s,14.0,N,NaN,NaN,NaN,NaN
14,Bahrain,15,5.0,Vettel,NaN,55.0,+1 lap,0.0,1:35.566,NaN,203.871,1.0,24.0,18:49:08,24.626,24.626,20.0,1:32.056,1:32.056,NaN,NaN,6.0,12.0,01:33.2,1.763s,21.0,14.0,01:31.8,0.922s,26.0,14.0,01:32.8,2.178s,15.0,N,NaN,NaN,NaN,NaN
15,Bahrain,16,47.0,Schumacher,NaN,55.0,+1 lap,0.0,1:36.134,NaN,202.667,2.0,33.0,19:04:27,25.343,51.141,18.0,1:32.449,1:32.449,NaN,NaN,6.0,19.0,01:34.5,3.107s,16.0,18.0,01:33.3,2.450s,24.0,18.0,01:33.4,2.845s,14.0,N,NaN,NaN,NaN,NaN
16,Bahrain,17,10.0,Gasly,NaN,52.0,DNF,0.0,1:34.090,NaN,207.069,3.0,39.0,19:13:55,24.983,01:27.6,5.0,1:29.809,1:30.848,1:30.513,1:29.809,15.0,7.0,01:32.2,0.801s,23.0,9.0,01:31.5,0.636s,27.0,3.0,01:31.6,1.006s,13.0,N,NaN,NaN,NaN,NaN
17,Bahrain,18,6.0,Latifi,NaN,51.0,DNF,0.0,1:36.602,NaN,201.685,2.0,32.0,19:02:32,23.983,50.029,17.0,1:31.936,1:31.936,NaN,NaN,8.0,18.0,01:34.3,2.946s,22.0,19.0,01:33.4,2.553s,28.0,20.0,01:34.0,3.382s,16.0,N,NaN,NaN,NaN,NaN
18,Bahrain,NC,14.0,Alonso,NaN,32.0,DNF,0.0,1:36.063,NaN,202.816,2.0,29.0,18:57:13,24.775,49.148,9.0,1:30.249,1:30.863,1:30.595,1:30.249,15.0,16.0,01:33.9,2.478s,18.0,15.0,01:31.8,0.923s,24.0,15.0,01:32.8,2.243s,15.0,N,NaN,NaN,NaN,NaN
19,Bahrain,NC,9.0,Mazepin,NaN,0.0,DNF,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,1:33.273,1:33.273,NaN,NaN,7.0,20.0,01:35.0,3.581s,16.0,20.0,01:33.4,2.602s,19.0,19.0,01:33.6,3.045s,14.0,N,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Emilia Romagna,1,33.0,Verstappen,NaN,63.0,2:02:34.598,25.0,1:17.524,NaN,NaN,2.0,33.0,15:58:11,27:01.4,27:31.2,3.0,1:14.498,1:15.109,1:14.884,1:14.498,20.0,3.0,01:16.6,0.058s,21.0,14.0,01:17.0,1.448s,5.0,1.0,01:15.0,NaN,18.0,N,NaN,NaN,NaN,NaN
22,Emilia Romagna,2,44.0,Hamilton,NaN,63.0,+22.000s,19.0,1:16.702,NaN,NaN,4.0,33.0,16:24:48,01:05.9,27:10.9,1.0,1:14.411,1:14.823,1:14.817,1:14.411,23.0,2.0,01:16.6,0.041s,25.0,2.0,01:15.6,0.010s,26.0,3.0,01:15.5,0.557s,18.0,N,NaN,NaN,NaN,NaN
23,Emilia Romagna,3,4.0,Norris,NaN,63.0,+23.702s,15.0,1:18.259,NaN,NaN,2.0,33.0,15:59:06,26:25.0,26:55.6,7.0,1:14.875,1:15.009,1:14.718,1:14.875,15.0,13.0,01:17.9,1.371s,16.0,8.0,01:16.5,0.934s,23.0,2.0,01:15.4,0.456s,17.0,N,NaN,NaN,NaN,NaN
24,Emilia Romagna,4,16.0,Leclerc,NaN,63.0,+25.579s,12.0,1:18.379,NaN,NaN,2.0,33.0,15:58:28,26:49.5,27:20.5,4.0,1:14.740,1:15.413,1:14.808,1:14.740,19.0,6.0,01:16.9,0.345s,13.0,5.0,01:16.4,0.820s,28.0,5.0,01:15.7,0.780s,21.0,N,NaN,NaN,NaN,NaN

In [4]:
df.dtypes

Race                              object
POS                               object
No                               float64
Driver                            object
Car                              float64
Laps                             float64
Time/Retired                      object
PTS                              float64
Fastest Lap                       object
Time                             float64
Avg Speed                        float64
Num Stops                        float64
Stop Lap                         float64
Stop TOD                          object
Stop TIme                         object
Stop Total TIme                   object
Starting Grid Position           float64
Starting Grid Qualifying TIme     object
Q1 Time                           object
Q2 Time                           object
Q3 Time                           object
Qualifying Laps                  float64
Practice 1 Position              float64
Practice 1 Time                   object
Practice 1 Gap                    object
Practice 1 Laps                  float64
Practice 2 Position              float64
Practice 2 Time                   object
Practice 2 Gap                    object
Practice 2 Laps                  float64
Practice 3 Position              float64
Practice 3 Time                   object
Practice 3 Gap                    object
Practice 3 Laps                  float64
Sprint Y/N                        object
Sprint Position                  float64
Sprint Laps                      float64
Sprint Time                       object
Sprint Points                    float64
dtype: object

# Removing unwanted characters

In [5]:
# Remove '+' and 's' from Time/Retired column
df['Time/Retired']= df['Time/Retired'].astype('str')
df['Time/Retired']= df['Time/Retired'].map(lambda x: x.lstrip('+-'))
df['Time/Retired']= df['Time/Retired'].map(lambda x: x.rstrip('s'))

In [6]:
# Remove '+' and 's' from Practice 1 Gap column
df['Practice 1 Gap']= df['Practice 1 Gap'].astype('str')
df['Practice 1 Gap']= df['Practice 1 Gap'].map(lambda x: x.lstrip('+-'))
df['Practice 1 Gap']= df['Practice 1 Gap'].map(lambda x: x.rstrip('s'))

In [7]:
# Remove '+' and 's' from Practice 2 Gap column
df['Practice 2 Gap']= df['Practice 2 Gap'].astype('str')
df['Practice 2 Gap']= df['Practice 2 Gap'].map(lambda x: x.lstrip('+-'))
df['Practice 2 Gap']= df['Practice 2 Gap'].map(lambda x: x.rstrip('s'))

In [8]:
# Remove '+' and 's' from Practice 3 Gap column
df['Practice 3 Gap']= df['Practice 3 Gap'].astype('str')
df['Practice 3 Gap']= df['Practice 3 Gap'].map(lambda x: x.lstrip('+-'))
df['Practice 3 Gap']= df['Practice 3 Gap'].map(lambda x: x.rstrip('s'))

In [9]:
# Remove '+' and 's' from Sprint Time column
df['Sprint Time']= df['Sprint Time'].astype('str')
df['Sprint Time']= df['Sprint Time'].map(lambda x: x.lstrip('+-'))
df['Sprint Time']= df['Sprint Time'].map(lambda x: x.rstrip('s'))

In [10]:
#df.head(25)

In [11]:
#df.tail(50)

# Drop Columns

In [12]:
# *Might not need to drop this with scraped data*
# *Do we want to keep the SPRINT race data since it is only GB?*
df = df.drop(columns=['Car', 'Time'])

# Time Conversions

In [13]:
# Replace '1 lap' values with new value

In [14]:
# Replace 'DNF' values with new value

In [15]:
# convert 'Fastest Lap' from MM:SS to total seconds

In [16]:
# convert 'Stop TOD' from HH:MM:SS to total seconds

In [17]:
# convert 'Stop Time' from MM:SS to total seconds

In [18]:
# convert 'Stop Total Time' from MM:SS to total seconds

In [19]:
# convert 'Starting Grid Qualifying TIme' from MM:SS to total seconds

In [20]:
# convert 'Q1 Time' from MM:SS to total seconds

In [21]:
# convert 'Q2 Time' from MM:SS to total seconds

In [22]:
# convert 'Q3 Time' from MM:SS to total seconds

In [23]:
# convert 'Practice 1 Time' from MM:SS to total seconds

In [24]:
# convert 'Practice 2 Time' from MM:SS to total seconds

In [25]:
# convert 'Pratice 3 Time' from MM:SS to total seconds

In [26]:
# convert 'Q1 Time' from MM:SS to total seconds

In [27]:
# convert 'Q1 Time' from MM:SS to total seconds

In [28]:
# convert 'Q1 Time' from MM:SS to total seconds

In [29]:
# Test time conversion to total seconds for 'Time/Retired' for Hamilton
# ts = df['Time/Retired'].loc[0]
# secs = sum(float(x) * 60 ** i for i, x in enumerate(reversed(ts.split(':'))))
# print(secs)

In [30]:
# Test time conversion to total seconds 'Fastest lap' for Hamilton
# tot_s = df['Fastest Lap'].loc[0]
# seconds = sum(float(x) * 60 ** i for i, x in enumerate(reversed(tot_s.split(':'))))
# print(seconds)

# Removing Decimals

In [31]:
df.dtypes

Race                              object
POS                               object
No                               float64
Driver                            object
Laps                             float64
Time/Retired                      object
PTS                              float64
Fastest Lap                       object
Avg Speed                        float64
Num Stops                        float64
Stop Lap                         float64
Stop TOD                          object
Stop TIme                         object
Stop Total TIme                   object
Starting Grid Position           float64
Starting Grid Qualifying TIme     object
Q1 Time                           object
Q2 Time                           object
Q3 Time                           object
Qualifying Laps                  float64
Practice 1 Position              float64
Practice 1 Time                   object
Practice 1 Gap                    object
Practice 1 Laps                  float64
Practice 2 Position              float64
Practice 2 Time                   object
Practice 2 Gap                    object
Practice 2 Laps                  float64
Practice 3 Position              float64
Practice 3 Time                   object
Practice 3 Gap                    object
Practice 3 Laps                  float64
Sprint Y/N                        object
Sprint Position                  float64
Sprint Laps                      float64
Sprint Time                       object
Sprint Points                    float64
dtype: object

# Formatting Columns

In [32]:
df = df.style.format({
    'No': '{:.0f}'.format,
    'Laps': '{:.0f}'.format,
    'PTS': '{:.0f}'.format,
    'Avg Speed': '{:.3f}'.format,
    'Num Stops': '{:.0f}'.format,
    'Stop Lap': '{:.0f}'.format,
    'Starting Grid Position': '{:.0f}'.format,
    'Qualifying Laps': '{:.0f}'.format,
    'Practice 1 Position': '{:.0f}'.format,
    'Practice 1 Laps': '{:.0f}'.format,
    'Practice 2 Position': '{:.0f}'.format,
    'Practice 2 Laps': '{:.0f}'.format,
    'Practice 3 Position': '{:.0f}'.format,
    'Practice 3 Laps': '{:.0f}'.format,
    'Sprint Position': '{:.0f}'.format,
    'Sprint Laps': '{:.0f}'.format,
    'Sprint Points': '{:.0f}'.format

})
df